### ISSUE TITLE
CronExpression Error

### ISSUE THREAD

**Issue by capritzl** [rvrolyk/SleepNumberController#6]
I am receiving the following error from the Sleep Number App, in the Log.  I just updated to the new release.

java.lang.RuntimeException: CronExpression '38 /120 * * * ?' is invalid. on line 411 (method updated)

**Comment by rvrolyk** [comment]
That probably needs some input guards.  120 needs to be less than 60 (0-59) as it's the number of minutes in an hour.  Currently intervals longer than an hour are not supported.  If this is something you want I could look at adding a toggle to allow creating the full cron expression instead of just the minute portion.

**Comment by capritzl** [comment]
Thanks for the info.  I set the refresh interval to 59 minutes.  This did indeed eliminate the error message.  No need for additional changes.

**Comment by rvrolyk** [comment]
Sounds good.  I went ahead and added a note to the input field noting it needs to be 0-59 so whenever the next release is created that will be present.  If you end up wanting something more flexible let me know.
